
create table Link 
(link_id bigint generated by default as identity (start with 1), 
description varchar(255), 
posted_on timestamp, 
title varchar(255) not null, url varchar(255) not null, posted_by bigint not null, primary key (link_id));
create table User (user_id bigint generated by default as identity (start with 1), email_id varchar(255) not null, password varchar(255) not null, receive_email_feed bit not null, userName varchar(255) not null, primary key (user_id), unique (userName), unique (email_id));
alter table Link add constraint FK24241A901564AC foreign key (posted_by) references User;
